name: Lexer Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  TERM: xterm-256color

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install compiler
        run: |
          sudo apt update
          sudo apt install -y g++

      - name: Build tests
        run: |
          g++ -std=c++17 \
            main/tests/lexer_test.cc \
            main/language/lexer/lexer.cc \
            main/language/lexer/line_lexer.cc \
            -Imain/language/lexer \
            -Imain/language \
            -Imain/utils \
            -Imain/consts \
            -DTEST \
            -o lexer_test

      - name: Run tests
        run: |
          ./lexer_test || exit 1
